title: IRC Wiki
description: A wiki for IRC based on Github pages
show_downloads: false
comments: false
logo_url: /assets/images/logo.jpg
google_analytics:
git_branch: master
theme: 
use_github_wiki: false
use_prose_io: false
google_cse_token: 007197903287787072094:8rbvkeqo6qw
custom_sidebar: true
markdown:kramdown
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
