title: IRC Wiki
description: A wiki for IRC based on Github pages
show_downloads: false
comments: false
logo_url: https://i.pinimg.com/736x/48/bc/1a/48bc1ae88f43aa9845403d378ecdb830--wedding-hashtag-generator-being-used.jpg
google_analytics:
git_branch: master
theme: 
use_github_wiki: false
use_prose_io: false
google_cse_token: 007197903287787072094:8rbvkeqo6qw
custom_sidebar: true
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
